# Numpy - Numerical Python
1d- vector  []
2d- Matrices  [[]]
3d or more- tensors [[[]]]

### Helps to store array

### It  helps to perform basic maths, statitisal fuctionns, log functions, scientific calculation etc

 ### It is 50x faster as it has different location for function, list etc as copmpared to traditional python which is stored in same location


In [1]:
import numpy as np

In [2]:
arr1=np.array([])

In [8]:
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array([], dtype=float64)

In [10]:
my_list=[1,2,3,4,5]
print(my_list)
type(my_list)

[1, 2, 3, 4, 5]


list

In [14]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [15]:
a.dtype

dtype('int32')

In [23]:
myset={1,22,3,43}
b=np.array(myset)
b

array({1, 3, 22, 43}, dtype=object)

In [47]:
print('Structure is :',type(b))

Structure is : <class 'numpy.ndarray'>


In [25]:
b.dtype

dtype('O')

In [28]:
list1=[1,2,'rajana',4]
c=np.array(list1)
c

array(['1', '2', 'rajana', '4'], dtype='<U11')

In [29]:
type(c)

numpy.ndarray

In [30]:
c.dtype

dtype('<U11')

In [31]:
c.ndim

1

In [32]:
c.size

4

In [33]:
c

array(['1', '2', 'rajana', '4'], dtype='<U11')

In [34]:
a.shape   # shape of array

(5,)

In [35]:
c.shape

(4,)

# Arrays ca be of n dimesnsions


In [36]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [38]:
d=np.array(my_matrix)

In [39]:
type(d)

numpy.ndarray

In [40]:
d.dtype  # data type of elements

dtype('int32')

In [41]:
d.ndim

2

In [42]:
d.shape

(3, 4)

In [43]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
d.size  # total elemets in array

12

In [61]:
d_tensor=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]   #3d
print(d_tensor)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [55]:
type(d_tensor)

list

In [57]:
e=np.array(d_tensor)
e

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
e.ndim

3

In [59]:
e.shape

(2, 2, 3)

In [60]:
type(e)

numpy.ndarray

# Built in Methods -- lots of builts in ways to genrate arrays

## Reshape Arrays

In [63]:
d.shape # 2-d array above

(3, 4)

In [64]:
arr2=d.reshape((4,3))  # reshapes array

In [65]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
arr3=d.reshape((2,6))

In [67]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [68]:
arr3.shape

(2, 6)

In [69]:
# 12 sized elemets can be changed into  1x12,  12X1,  3x4,   4x3,  6x2,  2x6,   2x2x3, 2x3x2, 3x2x2,  1X4x3 , 3x4x1

d


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [71]:
arr4=d.reshape((1,12))

In [72]:
arr4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [73]:
arr4.shape

(1, 12)

In [111]:
arr5=arr4.reshape((1,4,3))
arr5

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

# Arange

The arrage() function helps to create an array with regularly spaced values within specidied range

In [76]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
np.arange(2,100,4)  # start , end , step

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [79]:
np.arange(0,11,2)  # start , end , step

array([ 0,  2,  4,  6,  8, 10])

In [84]:
np.arange(100,2,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [88]:
np.arange(-100,20,2)

array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82,  -80,
        -78,  -76,  -74,  -72,  -70,  -68,  -66,  -64,  -62,  -60,  -58,
        -56,  -54,  -52,  -50,  -48,  -46,  -44,  -42,  -40,  -38,  -36,
        -34,  -32,  -30,  -28,  -26,  -24,  -22,  -20,  -18,  -16,  -14,
        -12,  -10,   -8,   -6,   -4,   -2,    0,    2,    4,    6,    8,
         10,   12,   14,   16,   18])

In [89]:
np.arange(-100,20,-2)

array([], dtype=int32)

In [90]:
np.arange(100,20,2)

array([], dtype=int32)

# Zeros and Ones

In [81]:
np.zeros(19)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [82]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [92]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [98]:
f=np.ones((4,5,6))
f

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [99]:
type(f)

numpy.ndarray

In [100]:
f.shape

(4, 5, 6)

In [102]:
f.ndim

3

In [104]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Linspace

Return evenly spaced numbers over a specified interval

In [113]:
np.linspace(1,15) # default 50 observations # both start ad end are included inn array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [115]:
np.linspace(2,25,5,retstep=True)  # equally spaced 5 values  # retstep By default retstep is False

(array([ 2.  ,  7.75, 13.5 , 19.25, 25.  ]), 5.75)

In [119]:
np.linspace(1,15,3,retstep=True)

(array([ 1.,  8., 15.]), 7.0)

# eye and identity -- creates identity matrix

In [120]:
np.eye(5) # generates  2d array of 5x5 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [121]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [123]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [126]:
np.eye((5,5),dtype=int)

TypeError: 'tuple' object cannot be interpreted as an integer

In [127]:
np.identity((5,5),dtype=int)

TypeError: 'tuple' object cannot be interpreted as an integer

In [128]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [129]:
np.identity(5,int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [132]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Broadcasting in Array -- ability to access each and every elemnt of array is called brodcasting

In [138]:
x=np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [139]:
x.dtype

dtype('float64')

In [140]:
x *3 

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [141]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [142]:
x*6-2

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [147]:
z=np.ones(4)*4
print(z)
y=np.array(z-0.4, dtype=int)
y

[4. 4. 4. 4.]


array([3, 3, 3, 3])

In [150]:
type(y)

numpy.ndarray

In [152]:
arr1=np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [156]:
1/arr1

C:\Users\Rajan Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [157]:
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

# Use of Copy Function

In [158]:
arr2=arr1  # not recommeded as if you change arr2 later arr1 also changes
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [159]:
arr2[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
arr2[:10]=30 # Using idex slicicing to modify arr2
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [161]:
arr1

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [163]:
arr3=arr1.copy()  # generate a copy /  create a  backup # create new dats set for practise with help of these

In [164]:
arr3[10:]=100
arr3

array([ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

# Random number generation 


numpy has lot of ways to create random  number arrays

# rand

In [166]:
np.random.rand()

0.6801606967357624

In [181]:
np.random.rand(20)  # rand function will give uniform distribution  rage of values from 0 to 1 

array([0.99423805, 0.27385541, 0.11831132, 0.82957588, 0.72316924,
       0.83846703, 0.85876062, 0.75593596, 0.23274054, 0.37958018,
       0.66748028, 0.24534935, 0.66801795, 0.75672667, 0.15169541,
       0.19109891, 0.89743916, 0.50092162, 0.50582282, 0.39153868])

In [170]:
np.random.rand(10).reshape(2,5)  

array([[0.73438444, 0.77141985, 0.63030862, 0.57237088, 0.91380143],
       [0.30743289, 0.98340947, 0.14117673, 0.48837466, 0.07006052]])

In [ ]:
# Creating array from uniform distribution
new_arr=np.random.rand(5,3)
# 2 dimesion array of shape

In [204]:
new_arr

array([[0.94336923, 0.46916762, 0.13755806],
       [0.96078865, 0.25181304, 0.95289166],
       [0.87023961, 0.61305194, 0.84409911],
       [0.78410175, 0.85045513, 0.47148665],
       [0.13214055, 0.1577974 , 0.95103901]])

In [206]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')
import seaborn as sns

In [210]:
sns.distplot(new_rnr)
#sns.distplot([10,12,4,23,3,23,22,3])
plt.show()

NameError: name 'new_rnr' is not defined

In [185]:
# Creating array from normal distribution from   [-3,3], std =1  mean =0
new_arr2=np.random.randn(50)
# 2 dimesion array of shape

In [186]:
max(new_arr2)

2.7296577295385287

In [187]:
min(new_arr2)

-2.4257968202146625

In [188]:
new_arr2

array([-1.60231082, -0.59425754,  0.39735741,  0.89408142, -1.34605778,
        2.72965773,  0.93855797, -1.47819679, -0.86291741,  0.95201146,
       -1.02078542, -0.89687492,  1.2354152 ,  0.99523511, -1.27488834,
        1.76934683, -0.53470451, -1.41800096,  0.11154297,  0.35286718,
       -2.42579682,  0.58765224,  0.06950029,  0.30930832, -0.70627944,
       -2.02228949, -0.05823123,  1.69996333, -0.81038853,  1.27822356,
        1.34999909,  0.85258118, -0.11190749,  0.93175009, -1.00862334,
       -0.66106658, -0.15799818, -1.0575712 , -0.61952837,  0.52303394,
       -0.85127084, -1.18010816,  0.86131069,  0.04938119, -1.26656733,
        1.12720151,  2.36004731,  0.99410813, -1.67001176,  1.29014568])

# randint
#return radom numbers from low( inclusive) to high (not innclusive)

In [190]:
np.random.randint(1,100)       # third argument is number of values , by default it is 1

15

In [191]:
np.random.randint(1,100,23)  # geerating 23 values between 1 till 99

array([18, 82, 97, 37, 84, 18, 64, 37, 64, 46, 16, 98, 50, 63, 95,  3, 95,
       99,  7, 91, 62, 98,  1])

# array attributes and methods

In [199]:
arr=np.arange(20)
ranarr=np.random.randint(0,100,10)
ranarr

array([ 9,  2, 75, 51, 45, 88, 11, 12, 44, 29])

In [201]:
ranarr.max()

88

In [202]:
ranarr.min()

2

In [212]:
ranarr.argmax()

5

In [213]:
ranarr.argmin()

1

# Bracket Indexing and Slicing, Selection in Numpy

Simplest way to pick one or more elements of an array looks very similar to pytho lists:

In [215]:
arr= np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [216]:
len(arr)

18

In [217]:
arr[9] # get value at index 9 or 10th index , 11th position

55

In [218]:
arr[-1]

95

In [219]:
arr[1:11:2] # get values in range

array([15, 25, 35, 45, 55])

In [223]:
arr[-6:-1]

array([70, 75, 80, 85, 90])

# Filtering

In [230]:
arr1=np.array([1,2,1010,4,108,18,71,610])
arr1

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [231]:
arr1<100

array([ True,  True, False,  True, False,  True,  True, False])

In [234]:
np.where(arr1<100) # gives index position where 

(array([0, 1, 3, 5, 6], dtype=int64),)

In [241]:
np.where(arr1>100) # gives index position where arr1>100

(array([2, 4, 7], dtype=int64),)

In [242]:
np.where(arr1==100)

(array([], dtype=int64),)

 # Indexig a 2D array(matrices)
 ####  the general format is arr_2d[row,col]

In [243]:
arr_2d=np.array([[1,2,3],[12,13,14],[64,96,128]])

In [244]:
arr_2d

array([[  1,   2,   3],
       [ 12,  13,  14],
       [ 64,  96, 128]])

In [245]:
arr_2d.shape

(3, 3)

In [246]:
arr_2d.ndim

2

In [247]:
arr_2d[1:,:2]

array([[12, 13],
       [64, 96]])

In [248]:
arr_2d[1]

array([12, 13, 14])

In [ ]:
arr_2d[1]

In [250]:
arr_2d[0:2,1:]

array([[ 2,  3],
       [13, 14]])

In [251]:
arr_2d[:,2]

array([  3,  14, 128])

In [254]:
arr_2d[1:1,0:1]

array([], shape=(0, 1), dtype=int32)

In [258]:
arr_2d[1:2,1:2]

array([[13]])

In [259]:
arr_2d[1,1]

13

In [260]:
arr_2d[:,2]

array([  3,  14, 128])

In [261]:
arr_2d[:2,1:]

array([[ 2,  3],
       [13, 14]])

# Fancy Indexing

In [262]:
arr2d=np.arange(0,100).reshape(10,10)

In [263]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [265]:
arr2d[[6,3,8]]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [266]:
arr2d[:,[2,4,6,8]]

array([[ 2,  4,  6,  8],
       [12, 14, 16, 18],
       [22, 24, 26, 28],
       [32, 34, 36, 38],
       [42, 44, 46, 48],
       [52, 54, 56, 58],
       [62, 64, 66, 68],
       [72, 74, 76, 78],
       [82, 84, 86, 88],
       [92, 94, 96, 98]])

In [270]:
arr2d[1:6,[2,4,6,8]]

array([[12, 14, 16, 18],
       [22, 24, 26, 28],
       [32, 34, 36, 38],
       [42, 44, 46, 48],
       [52, 54, 56, 58]])

In [271]:
arr2d[[2,4,6,8],[2,4,6,8]]

array([22, 44, 66, 88])

# Selection

In [272]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [273]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [275]:
arr=np.arange(1,11)
arr1=arr>4
arr1

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [276]:
filtered_values=arr[arr1]
filtered_values

array([ 5,  6,  7,  8,  9, 10])

In [278]:
filtered_values1=arr[arr>4]

In [279]:
filtered_values1

array([ 5,  6,  7,  8,  9, 10])